baseURL = ""
languageCode = "en-us"
title = "Infinity | Comming Soon Hugo Template By Themefisher"
theme = "infinity hugo"
removePathAccents = true
themesDir = "themes"
publishDir = "public"

[params]
customHead = ""

  [params.navigation]
  logo = "images/logo.png"
  home = "Home"
  about = "About"
  service = "Services"
  contact = "Contact"

  [params.hero]
  enable = true
  bg = "images/header-bg.jpg"
  title = "BRING YOUR PRODUCT TO LIGHT"
  subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna"
  btnText = "Get Started"
  disableCountdown = false
  countdownYear = "2021"
  countdownMonth = "12"
  countdownDay = "31"

  [params.about]
  enable = true
  heading = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam ipsa recusandae consequatur veniam, reiciendis odit quia eaque vel eius a."
  description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ulla-mco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque, aspernatur."

    [[params.about.sliderItem]]
    image = "images/about/1.jpg"

    [[params.about.sliderItem]]
    image = "images/about/2.jpg"

    [[params.about.sliderItem]]
    image = "images/about/3.jpg"

    [[params.about.sliderItem]]
    image = "images/about/2.jpg"

  [params.service]
  enable = true
  title = "Find Better Solutions Build Better Products"
  subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et"

    [[params.service.serviceItem]]
    icon = "tf-strategy"
    title = "Fully Responsive"
    description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
    delay = "0s"

    [[params.service.serviceItem]]
    icon = "tf-circle-compass"
    title = "Speed Optimized"
    description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
    delay = "0.2s"

    [[params.service.serviceItem]]
    icon = "tf-anchor2"
    title = "Tons of Feature"
    description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
    delay = "0.4s"

    [[params.service.serviceItem]]
    icon = "tf-globe"
    title = "Fully SEO Optimized"
    description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
    delay = "0.6s"

    [[params.service.serviceItem]]
    icon = "tf-strategy"
    title = "Fully Responsive"
    description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
    delay = "0.8s"

    [[params.service.serviceItem]]
    icon = "tf-circle-compass"
    title = "Speed Optimized"
    description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
    delay = "1s"

    [[params.service.serviceItem]]
    icon = "tf-anchor2"
    title = "Tons of Feature"
    description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
    delay = "1.2s"

    [[params.service.serviceItem]]
    icon = "tf-globe"
    title = "Fully SEO Optimized"
    description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
    delay = "1.5s"

  [params.cta]
  enable = true
  bg = "images/call-to-action.jpg"
  title = "Subscribe to our mailing list"
  subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"

  [params.contact]
  enable = true
  title = "Get In Touch"
  subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex"
